import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./../styles/globals.css";
import PathnameWrapper from "@/components/PathnameWrapper";

const lato = Lato({
  variable: "--font-lato",
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} antialiased`}
      >
        <PathnameWrapper>
        {children}
        </PathnameWrapper>
      </body>
    </html>
  );
}
